export {default as Akun} from './akun'
export {default as Home} from './home'
export {default as AnalisaData } from './analisa_data'
export {default as Bansos} from './bansos'
export {default as Peta} from './peta'
export {default as Profile} from './profile'
export {default as Login} from './login'