export {default as TambahBansos} from './tambah-bansos'
export {default as Home} from './home'
export {default as AnalisaData } from './analisa_data'
export {default as Bansos} from './bansos'
export {default as Peta} from './peta'
export {default as Profile} from './profile'
export {default as Login} from './login'
export {default as AddBansos} from './tambah-bansos/bansos'
export {default as AddLokasi} from './tambah-bansos/lokasi'
export {default as AddPenerima} from './tambah-bansos/penerima'